apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ui2nbuxoc-nodejs 
  janus-idp.io/tekton: ui2nbuxoc-nodejs
  backstage.io/kubernetes-id: ui2nbuxoc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ui2nbuxoc-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  